name: "编译和上传"

on:
  workflow_dispatch:

jobs:
  build_upload:
    permissions:
        contents: write
        packages: write
        pull-requests: "read"
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: 安装依赖环境
          shell: bash
          working-directory: builder
          run: bash stage1.sh

        - name: 安装自定义节点
          shell: bash
          working-directory: builder
          run: bash stage2.sh

        - name: 编译打包
          shell: bash
          working-directory: builder
          run: bash stage3.sh

        - name: 上传文件发布
          uses: svenstaro/upload-release-action@v2
          with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: "builder/*.7z*;builder/*.zip*"
                tag: "latest"
                overwrite: true