name: "Build & Upload Package"

on:
  workflow_dispatch:

jobs:
  build_upload:
    permissions:
        contents: write
        packages: write
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: Build Process
          shell: bash
          working-directory: builder
          run: |
            bash stage1.sh
            bash stage2.sh
            bash stage3.sh

        - name: Move Artifacts to Root
          shell: bash
          run: |
            # 将分卷文件移动到仓库根目录
            mv builder/ComfyUI_Windows_portable*.7z.* . || true
            mv builder/models*.zip.* . || true

        - name: Verify Artifacts
          shell: bash
          run: |
            echo "=== 根目录文件 ==="
            ls -lah *.7z.* *.zip.*
            echo "=== 分卷校验 ==="
            7z l ComfyUI_Windows_portable_cu126.7z.001
            7z l models.zip.001

        - name: Upload Release Assets
          uses: softprops/action-gh-release@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: |
              ComfyUI_Windows_portable_cu126.7z.*
              models.zip.*
            tag_name: "v$(date +%Y%m%d)"
            generate_release_notes: true
            fail_on_unmatched_files: true