name: "Build & Upload Package"

on:
  workflow_dispatch:

jobs:
  build_upload:
    permissions:
        contents: write
        packages: write
        pull-requests: read
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4

        - name: Stage 1-3 Build Process
          shell: bash
          working-directory: builder
          run: |
            bash stage1.sh
            bash stage2.sh
            bash stage3.sh

        - name: Verify Artifacts
          shell: bash
          run: |
            # 显示完整的文件树结构
            cd $GITHUB_WORKSPACE
            echo "=== 完整目录结构 ==="
            ls -lahR
            echo "=== 压缩包详情 ==="
            7z l *.7z*
            7z l *.zip*

        - name: Upload Release Assets
          uses: softprops/action-gh-release@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            files: |
              *.7z.*
              *.zip.*
            tag_name: "build-${{ github.run_id }}"
            generate_release_notes: true